apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-storage-pvc
spec:
  accessModes:
    - ReadWriteMany
  # storageClassName: efs-sc
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi