apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-storage-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client
#   volumeName: jenkins-storage-pv